Repository aerogear/charmil, pull requests merged in 2021-08, with the labels that each got.

#205 refactor(charmil-crud): change template format and update import paths
  cli/internal/cmd/crud/crud.go
  cli/internal/template/crud/create/create.tmpl
  cli/internal/template/crud/create/run.tmpl
  cli/internal/template/crud/delete/delete.tmpl
  cli/internal/template/crud/delete/run.tmpl
  cli/internal/template/crud/describe/describe.tmpl
  cli/internal/template/crud/describe/run.tmpl
  cli/internal/template/crud/list/list.tmpl
  cli/internal/template/crud/list/run.tmpl
  cli/internal/template/crud/root.tmpl
  cli/internal/template/crud/use/run.tmpl
  cli/internal/template/crud/use/use.tmpl
  go.mod
  go.sum
Labels: requires-release

#209 docs: update i18n docs
  docs/src/charmil_i18n.md
Labels: documentation

#207 feat: add command in charmil cli
  cli/cmd/charmil/locales/en/add.en.yaml
  cli/internal/cmd/add/add.go
  cli/internal/cmd/crud/crud.go
  cli/internal/cmd/root/root.go
  cli/internal/common/generate/generate.go
  cli/internal/common/modname/modname.go
  cli/internal/template/add/cmdname.en.yaml
  cli/internal/template/add/cmdname.tmpl
  cli/internal/template/add/tmpl.go
  docs/src/charmil_cli.md
Labels: enhancement, requires-release

#219 chore: refactor core package
  cli/cmd/charmil/main.go
  cli/internal/cmd/add/add.go
  cli/internal/cmd/crud/crud.go
  cli/internal/cmd/init/init.go
  cli/internal/cmd/root/root.go
  cli/internal/template/add/cmdname.tmpl
  cli/internal/template/crud/create/create.tmpl
  cli/internal/template/crud/create/run.tmpl
  cli/internal/template/crud/delete/delete.tmpl
  cli/internal/template/crud/delete/run.tmpl
  cli/internal/template/crud/describe/describe.tmpl
  cli/internal/template/crud/describe/run.tmpl
  cli/internal/template/crud/list/list.tmpl
  cli/internal/template/crud/list/run.tmpl
  cli/internal/template/crud/root.tmpl
  cli/internal/template/crud/use/run.tmpl
  cli/internal/template/crud/use/use.tmpl
  cli/pkg/factory/default.go
  cli/pkg/factory/factory.go
  core/commands/.keep
  core/utils/color/color.go
  core/utils/iostreams/iostreams.go
  core/utils/localize/i18n.go
  core/utils/localize/localize.go
  core/utils/logging/logger.go
  core/utils/logging/std_logger.go
  docs/images/charmil_validator.png
  docs/src/charmil_commands.md
  docs/src/charmil_factory.md
  docs/src/charmil_i18n.md
  docs/src/charmil_logger.md
  docs/src/charmil_validator.md
  starter/cmd/cli/main.go
  starter/pkg/cmd/completion/bash/bash.go
  starter/pkg/cmd/completion/completion.go
  starter/pkg/cmd/completion/fish/fish.go
  starter/pkg/cmd/completion/zsh/zsh.go
  starter/pkg/cmd/root/root.go
  starter/pkg/factory/default.go
  starter/pkg/factory/factory.go
  website/sidebars.js
Labels: documentation, enhancement, requires-release

#223 feat: example builder utility
  core/utils/example_builder/builder.go
  docs/src/charmil_utils.md
Labels: enhancement, requires-release, publish-website
